### ISSUE TITLE
STL for Case

### ISSUE THREAD

**Issue by laurensvane** [mmakaay/esphome-smartmeter#1]
Not a real issue, but is it possible to share the stl file for printing the box as shown in the picture?
Would be nice to give it a nice fitting box.

**Comment by mmakaay** [comment]
The case is not 100% ready, design-wise, but quite usable as you saw in the picture.
I will upload what I've got so far.

**Comment by mmakaay** [comment]
I added my STL files to the project in the enclosure/ folder.
