### ISSUE TITLE
Schematic missing

### ISSUE THREAD

**Issue by szkrisz** [mmakaay/esphome-smartmeter#11]
Can you please reupload the schematic.png currently it is unreadable.
Thank You!

**Comment by wimjanse** [comment]
same question as above, please re upload the schematic, file seems to be corrupted

**Comment by mmakaay** [comment]
I did update the schematic, but forgot to report back here.
The https://github.com/mmakaay/dsmr-reader-for-esphome/blob/main/PCB/schematic.png in its current form should be readable. Feel free to re-open when you still have issues with it.
