### ISSUE TITLE
EasyEDA Project

### ISSUE THREAD

**Issue by WebSpider** [mmakaay/esphome-smartmeter#2]
Hi!

The september version of this repo had an EasyEDA project ZIP in it.This was much appreciated :)
Would it be possible to add this again?

**Comment by mmakaay** [comment]
I totally missed this request, sorry for that.
I just made a backup export for the EasyEDA project and added it to the repository:
https://github.com/mmakaay/dsmr-reader-for-esphome/blob/main/PCB/EasyEDA_project_backup.zip
