### ISSUE TITLE
RJ12 Partnumber

### ISSUE THREAD

**Issue by Sfunzer** [mmakaay/esphome-smartmeter#5]
Hi!

An easy/quick one: do you have a part number for the RJ12 socket. I can't seem to find the right one.

Thanks!

**Comment by thed6bel** [comment]
Hello, 
i ordered this one : 

https://fr.aliexpress.com/item/4000252589302.html?spm=a2g0o.order_list.order_list_main.165.3fa35e5b7ndciB&gatewayAdapt=glo2fra

:-)

**Comment by PexJensen** [comment]
> Hello, i ordered this one :

And it fits perfectly.

**Comment by Hoffnungsthal** [comment]
After a long search I found this one:

https://www.conrad.de/de/p/econ-connect-mjusn66gab-modular-einbaubuchse-mjusn66gab-buchse-einbau-horizontal-pole-6-schwarz-1-st-1311387.html

**Comment by mmakaay** [comment]
I ordere mine off Ali. Two different sets. Black and grey ones. The black ones are the hardest to fit on the holes, but they do fit. They grey ones fit perfectly. So I guess as long as the footprint looks like the one on my board design, it should be okay.
